apiVersion: apps/v1
kind: Deployment
metadata:
  name: michapp
  labels:
    app: michapp
    release: APPNAME
spec:
  selector:
    matchLabels:
      app: michapp
  replicas: 1
  template:
    metadata:
      labels:
        app: michapp
    spec:
      containers:
      - name: michapp
        image: nm-mgmt.iic.pl.ibm.com:8500/default/michapp-APPNAME:BUILD_NUMBER
        ports:
        - containerPort: 80
          name: appport
      nodeSelector:
        beta.kubernetes.io/arch: amd64
